Repository babajka/babajka-markup, pull requests merged in 2018-04, with the labels that each got.

#27 About page
  gulpfile.js
  src/about/about.ejs
  src/about/about.scss
  src/about/team.json
  src/about/teammate.ejs
  src/components/select/select.ejs
  src/footer/footer.ejs
  src/footer/footer.scss
  src/images/talaka_logo.png
  src/images/team/badziej.jpg
  src/images/team/bohdan.jpg
  src/images/team/drapegnik.jpg
  src/images/team/placeholder.png
  src/images/team/tonia.jpg
  src/images/team/vika.jpg
  src/navbar/navbar.scss
  src/templateVariables.json
  stubs/development.html
Labels: feature, not ready yet, page

#34 Refactoring for proper static delivery
  .gitignore
  gulpfile.js
  mypatch.patch
  package.json
  src/404/404.ejs
  src/about/about.ejs
  src/about/team.json
  src/article-page/article-page.ejs
  src/components/select/author.ejs
  src/components/select/select.ejs
  src/head/head.ejs
  src/images/team/badziej.jpg
  src/main-page/main-page.ejs
  src/navbar/navbar.ejs
  src/stubs/development.ejs
  src/templateVariables.json
  static/images/logo/favicon-colored.png
  static/images/logo/turq-transparent.png
  static/images/mock/mort.jpg
  static/images/mock/photo2.jpg
  static/images/mock/photo3.jpg
  static/images/mock/photo4.jpg
  static/images/mock/photo5.jpg
  static/images/mock/photo6.jpg
  static/images/mock/photo8.jpg
  static/images/mock/vajc.jpg
  static/images/mock/volski.jpg
  static/images/references/15_icon.png
  static/images/references/kurilka_icon.png
  static/images/references/talaka_logo.png
  static/images/team/anisimava.jpg
  static/images/team/badziej.jpg
  static/images/team/bohdan.jpg
  static/images/team/dabranskaja.jpg
  static/images/team/drapegnik.jpg
  static/images/team/halukhina.jpg
  static/images/team/mihniuk.jpg
  static/images/team/placeholder.png
  static/images/team/shylak.jpg
  static/images/team/sivykh.jpg
  static/images/team/tonia.jpg
  static/images/team/vika.jpg
  static/images/team/yaromka.jpg
  stubs/README.md
  stubs/static-prod/favicon-colored.png
  stubs/static-prod/logo-turq-transparent.png
  stubs/static-prod/talaka_logo.png
Labels: refactor

#35 Error 500 static page
  src/stubs/500.ejs
  src/stubs/development.ejs
  src/stubs/stubs.scss
  src/variables.scss
Labels: page

#36 About page and team photos
  src/about/about.ejs
  src/about/team.json
  src/about/teammate.ejs
  static/images/placeholders/user.png
  static/images/team/anisimava.jpg
  static/images/team/badziej.jpg
  static/images/team/bohdan.jpg
  static/images/team/dabranskaja.jpg
  static/images/team/drapegnik.jpg
  static/images/team/halukhina.jpg
  static/images/team/mihniuk.jpg
  static/images/team/shylak.jpg
  static/images/team/sivykh.jpg
  static/images/team/tonia.jpg
  static/images/team/vika.jpg
  static/images/team/yaromka.jpg
Labels: fix, refactor

#32 Remake article page markup
  src/article-page/article-card/article-card.ejs
  src/article-page/article-card/article-card.scss
  src/article-page/article-page.ejs
  src/article-page/article-page.scss
  src/variables.scss
  stubs/static-prod/styles/assets.min.css
Labels: page
